#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Constantin Luckenbach"
email = "cluckenbach@protonmail.com"

[ui]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
