#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Constantin Luckenbach"
email = "cluckenbach@protonmail.com"

[ui]
editor = "nvim"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ":builtin"

[signing]
behavior = "own"
backend = "gpg"
